server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory-service
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@discovery-server:8761/eureka